from enum import IntEnum
from cv2.typing import MatLike

class ImageFormat(IntEnum):
    # uint8
    GRAY8 = ...
    SRGB = ...
    SRGBA = ...
    SBGRA = ...
    # uint16
    GRAY16 = ...
    SRGB48 = ...
    SRGBA64 = ...
    # float32
    VEC32F1 = ...
    VEC32F2 = ...

class Image:
    def __init__(
        self,
        image_format: ImageFormat,
        data: MatLike,
        ) -> None: ...
